//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperationDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int CandidateId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhnNum { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string UnivName { get; set; }
        public string ClgName { get; set; }
        public string Branch { get; set; }
    }
}
